require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - sevencop

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Sevencop/AutoloadOrdered:
  Enabled: true

Sevencop/HashLiteralOrder:
  Enabled: true

Sevencop/MethodDefinitionMultilineArguments:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
